### ISSUE TITLE
New UI Design

### ISSUE THREAD

**Issue by SalGnt** [Arcath/jekyll-atom#13]
I think that the interface of the package is not well developed, IMHO there is too much waste of space. A new design for the Toolbar and the Manage tab would be great.

This is my first attempt to redesign the Toolbar, I hope you will like it!
 
![jekyll-atom-toolbar-new](https://cloud.githubusercontent.com/assets/884093/6092751/dea43fe8-aeec-11e4-8cd1-b66dda20e537.png)

**Comment by Arcath** [comment]
Yeah, I was thinking after using the notifications system in https://github.com/Arcath/sass-watch that I could drop the console from the toolbar and use notifications to keep the user informed about the status of the server.

I've got a couple of bugs to work out first with the way I use the emitter but I am more than happy to revist the UI

**Comment by SalGnt** [comment]
Great! Here is the concept I made for the Manage tab.

![jekyll-atom-manage-new](https://cloud.githubusercontent.com/assets/884093/6146336/d6d6de5e-b1eb-11e4-9876-d259db11ae08.png)

**Comment by Arcath** [comment]
I've started working on the new UI and this is what I've got so far.

![screen shot 2015-02-11 at 14 32 01](https://cloud.githubusercontent.com/assets/19609/6148592/d1728832-b1fa-11e4-8fe1-b7582ee4f968.png)

**Comment by Arcath** [comment]
Most of the UI has been removed in 1.0.0
