### ISSUE TITLE
Uncaught Error: spawn jekyll ENOENT

### ISSUE THREAD

**Issue by kangqf** [Arcath/jekyll-atom#14]
I get this error in console when Attempt to start the Jekyll server from within Atom.of course i had add the jekyll path C:\ProgramFiles\Ruby21-x64\bin; to my sytem path.And get this picture.
![image](https://cloud.githubusercontent.com/assets/5372027/6101624/19ed6810-b062-11e4-96c3-6697854d7cf7.png)

**Comment by kangqf** [comment]
Also i can run jekyll serve -w in my system console. It's no error.

**Comment by Arcath** [comment]
Sounds like you need to set the Jekyll binary in settings.

Atom doesn't use the system/user PATH so some commands need to be given as the complete path to the binary.

**Comment by kangqf** [comment]
But when i type  `process.env.PATH` in Atom console line I can find C:\ProgramFiles\Ruby21-x64\bin; Is it mean that the path is reachable in Atom ? if not how can i do to set the Jekyll binary in settings?

**Comment by Arcath** [comment]
I had many weird issues with PATH working/not working which is why I added the setting for the Binary Path.

If you go into settings, packages, jekyll you should see all the settings listed there.

There is currently a bug where the settings wont appear until after a package has been activated, the work around for now in jekyll-atom is to open the toolbar before going into settings.

**Comment by kangqf** [comment]
Ok,get it,An other question , how can i press command key in windows ?

**Comment by kangqf** [comment]
Also,when i click stop server ,i still can access the 127.0.0.1:4000 although it show Stopping Server....kill(7712)

**Comment by kangqf** [comment]
When i upgrade the Atom to the most version,may be some api changed as it shows 
![image](https://cloud.githubusercontent.com/assets/5372027/6129691/372f3f9c-b17b-11e4-8469-2ee0ed99cbbf.png)

**Comment by Arcath** [comment]
Seems the issue is that this commit https://github.com/Arcath/jekyll-atom/commit/f82bc8ccbada42f518308aca3ded5a0be69faef4 isn't in the apm release. I've just pushed 0.4.3 which should be fix that issue.

**Comment by Arcath** [comment]
Has updating to 0.4.3 solved your issues?

**Comment by kangqf** [comment]
It still could not stop the server by clicking the `stop server` botton

**Comment by Arcath** [comment]
Sounds like issues with being able to handle child processes on windows, will do some testing as soon as I can

**Comment by Arcath** [comment]
Now that 1.0.0 doesn't use a _persistent_ child_process this should not be an issue any more
