### ISSUE TITLE
Code highlight issue -- support Jekyll front matter

### ISSUE THREAD

**Issue by fulldecent** [Arcath/jekyll-atom#16]
MOVED FROM https://github.com/atom/atom/issues/5745#issuecomment-76166789

Jekyll front matter may be added to the top of any file and it is signified by `---` and `---` to contain extra content.

This is erroneously being interpreted as HTML by Atom. In this example you can see the `&` symbol showing an error because it is not valid HTML.

![screen shot 2015-02-25 at 2 31 36 pm](https://cloud.githubusercontent.com/assets/382183/6378706/12f8eb60-bcfb-11e4-8620-770c889f078e.png)

**Comment by Arcath** [comment]
This seems to be part of atom now. Can you confirm?

**Comment by fulldecent** [comment]
Yes, works great, thanks!
