### ISSUE TITLE
Support: Custom properties on YAML front matter

### ISSUE THREAD

**Issue by RafaAguilar** [Arcath/jekyll-atom#18]
Hi there, **excellent** job on package BTW,

see if you create a new post the props are:

```xml
---
layout: post
title: "TITLE OF POST"
date: "2015-03-31"
---
```

I would love(somebody else too, for sure) if i can add some properties, e.g.to get this:

```xml
---
layout: post
title: "TITLE OF POST"
date: "2015-03-31"
author: rafa_aguilar
published:true
comments:true
---
```

**Comment by Arcath** [comment]
You can set [front matter defaults](http://jekyllrb.com/docs/configuration/#front-matter-defaults) in Jekyll, that might be worth looking into for this.
