### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [Arcath/jekyll-atom#22]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.4.3`) of this package:

1. Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `<pack-name>` package
1. If you would like your pane item with class `<ClassName>` to support modified behavior, please implement a `::onDidChangeModified()` method. If not, ignore this message. `::on` methods for items are no longer supported.
1. If you would like your pane item with class `<ClassName>` to support title change behavior, please implement a `::onDidChangeTitle()` method. `::on` methods for items are no longer supported. If not, ignore this message.
1. Call ::getActiveTextEditor instead
1. atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.
1. Use `Project::getDirectories()[0]?.resolve()` instead
1. Use TextEditor::getLastCursor() instead

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by Arcath** [comment]
Aiming to fix with version 1.0.0 (see #26)

**Comment by Arcath** [comment]
Fixed by #26
