### ISSUE TITLE
Can´t Enable / Uninstall / Install

### ISSUE THREAD

**Issue by Siroguh** [Arcath/jekyll-atom#23]
Maybe its a bug from atom, but its the unique package in which that is happening...
![captura de pantalla 2015-06-04 a las 14 43 31](https://cloud.githubusercontent.com/assets/1921626/7984265/16f77838-0ac8-11e5-81d0-842eaed64509.png)

**Comment by Arcath** [comment]
Most likely an issue with some depracations in 0.4.3 version 1.0.0 will fix this (see #26)

**Comment by Arcath** [comment]
Has 1.0.0 fixed this?
