### ISSUE TITLE
Using the server toolbar or the build option does not generate _site

### ISSUE THREAD

**Issue by shadowlightwolf89** [Arcath/jekyll-atom#27]
As the title says, if I use the toolbar to start a server, or if I use the build option, neither generates the _site folder, yet it says build complete, I am very confused.

**Comment by Arcath** [comment]
What do you have your jekyll build command set to in config?

What OS are you running?

**Comment by shadowlightwolf89** [comment]
I have windows OS, and the build command is default.

**Comment by Arcath** [comment]
On my 8.1 install I have it set to `C:\Ruby22\bin\jekyll build` obviously that's because I installed Ruby to C:\Ruby22

**Comment by shadowlightwolf89** [comment]
I'll try that, and let you know if that works, though, I installed mine to Ruby21 heh

**Comment by shadowlightwolf89** [comment]
it say not valid, I even tried changing it to C:\Ruby21\bin\jekyll.bat build and that didn't work either.

**Comment by Arcath** [comment]
Try ` C:\Ruby21\lib\ruby\gems\2.1.0\gems\jekyll-2.5.3\bin\jekyll, build` its an array so the comma should be there, not sure why its not in what I copied out of my settings.

**Comment by shadowlightwolf89** [comment]
When I put in a comma, it says that "C:\Ruby21\lib\ruby\gems\2.1.0\gems\jekyll-2.5.3\bin\jekyll" is not valid, it does not include the build part.

**Comment by shadowlightwolf89** [comment]
btw I just upgraded to ruby 2.2.0 so my ruby is now installed at Ruby22 also

**Comment by shadowlightwolf89** [comment]
really ~.~ I just put in "C:\Ruby22\bin\jekyll.bat, build" and that worked, I am so confused.

**Comment by Arcath** [comment]
Yeah getting the child process to work, particularly on windows has been a real pain. Glad its sorted!

**Comment by shadowlightwolf89** [comment]
Question, so I just installed a dual boot OS with my previous Windows and Linux Mint, how different is the set up going to be for Linux?
