### ISSUE TITLE
Possibility to utilize multiple _posts directories?

### ISSUE THREAD

**Issue by shadowlightwolf89** [Arcath/jekyll-atom#28]
I typically work with multiple post directories, namely the _posts is under a folder for each category, is there a way to make the add new post command choose which directory to put it in, rather than just putting it in a single, pre-chosen directory?

**Comment by Arcath** [comment]
New post supports `_posts` and `_drafts` which is all Jekyll supports for posts. Have you got Jekyll looking in more directories?
