### ISSUE TITLE
adding custom yaml frontmatter as default

### ISSUE THREAD

**Issue by shadowlightwolf89** [Arcath/jekyll-atom#29]
I usually have several things in my YAML front matter alongside what you have in there by default, is there a way to add more default front matter, or would you be able to add a setting for adding default front matter?

The one thing I am really trying to figure out right now is how to add a time string to the front matter alongside the date, so it would read like this

date: 2015-06-25  4:00:00

that makes sorting posts that are on the same day easier.

**Comment by Arcath** [comment]
It is possible to set defaults for the front matter in jekyll see http://jekyllrb.com/docs/configuration/#front-matter-defaults

In #41 I have changed the generated date to contain the time
