### ISSUE TITLE
subdirs and dirs outside the main

### ISSUE THREAD

**Issue by shadowlightwolf89** [Arcath/jekyll-atom#30]
Okay, I know I'm making a lot of issues today, but I figured each thing should be it's own separate issue XD

Anyways, this issue is about the directory format I use for my jekyll blogs, and how I might be able to keep using it while also using your package...

See, I have what I call a grandmaster github set up, basically, I have the grandmaster folder, and under that folder are two folders, source and pages, source is where I write my posts and holds the jekyll source stuff, pages is where my jekyll compiles and outputs my jekyll site, this makes it easier when dealing with github pages.

So, the issue here is the way your package handles the directory structure, it requres that the main folder be your jekyll source, I'm not sure how it handles compiling outside the main directory though, I haven't tried that yet.

So I'm hoping there's a way to keep this all easy and useable XD

**Comment by Arcath** [comment]
This should be fixed by the work for #47 where jekyll-atom respects source/destination config.
