### ISSUE TITLE
Problem with auto update under Windows 8.1 64 bits

### ISSUE THREAD

**Issue by gseizilles** [Arcath/jekyll-atom#31]
Hi, thanks for jekyll-atom package, thats pretty useful for me.

However, when I launch the jekyll server I got an error about jekyll binary
![clipboard](https://cloud.githubusercontent.com/assets/8041658/8483090/63f53b02-20ee-11e5-919d-44f667afa60c.jpg)
I am under Windows 8.1 64 bits and I know that my command "jekyll build --watch" does not work for me, I guess because my user folder has some diacritics caracters: "Grégoire" (this causes some problems for some Python libs).
However, the "jekyll build" commands works well and the localhost:3000 server also works well.

Do you see a solution to solve this problem?

Thanks

**Comment by Arcath** [comment]
You can change the build command in settings. I have mine set to `C:\Ruby22\bin\jekyll.bat, build` on my Wndows 8.1 x64 machine. Your path will depend on where you installed ruby and your gems.

**Comment by gseizilles** [comment]
thanks it works
