### ISSUE TITLE
Multiple Build Commands? 

### ISSUE THREAD

**Issue by huphtur** [Arcath/jekyll-atom#38]
Possible to add (and select before starting server) multiple build commands?
- `jekyll, build`
- `jekyll, build, --drafts`
- etc.

**Comment by Arcath** [comment]
Would this be something you wanted to use per project?

I'm thinking of putting project specific things into your `_config.yml`

**Comment by Arcath** [comment]
1.1.0 added support for you setting your build command in your `_config.yml`
