### ISSUE TITLE
Jekyll Binary Path errors -- how to set this package to use the "bundle exec jekyll serve" command?

### ISSUE THREAD

**Issue by fusion809** [Arcath/jekyll-atom#39]
Hi,

Whenever I edit my Jekyll site's files I receive an error message entitled "Jekyll Binary Incorrect":
![Jekyll Binary Incorrect](http://i.imgur.com/945E5gt.png)
I'm guessing this means that my settings are not correctly set. I know that:
`bundle exec jekyll serve`
starts the Jekyll server without issue on my machine. My knowledge of how to edit Atom's settings and the settings of its packages is in its infancy, so please keep that in mind when ya respond. I saw [this](https://github.com/Arcath/jekyll-atom#configuring) part of this repo's README but it was not particularly helpful as I do not know where to set `Build Command` and even when I do set it I do not know how to set in order for it to run `bundle exec jekyll serve`. 

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
I just saw #37 and added `bundle, exec, jekyll, serve` to my Build Command (in the Settings of this package, which I set in the interface of Atom, refer to the screenshot below if you are confused by my phrasing) and I still received this Jekyll Binary Incorrect error. 

![Jekyll settings](http://imgur.com/kjKsjno.png)

**Comment by Arcath** [comment]
Atom uses a wierd $PATH I've had issues with it in another of my packages. Try something like:

```
/full/path/to/bundle/bin/bundle, exec, jekyll, build
```

you __need__ to build jekyll and not serve it. the package serves it inside the atom process and runs your command every save.

**Comment by fusion809** [comment]
Well I'll be it is working, thanks!
