### ISSUE TITLE
Jekyll code not highlighting?

### ISSUE THREAD

**Issue by tjkohli** [Arcath/jekyll-atom#44]
#16 This issue still exists for me. Any suggestions?

I have Atom 1.4.2 and Frontmatter & Jekyll tags are not being highlighted. In fact, they are rendering as "basic" HTML.

![screen shot 2016-02-01 at 10 34 41 pm](https://cloud.githubusercontent.com/assets/7361247/12739116/70faf6d6-c934-11e5-84c7-73c6d0520968.png)

Any help would be appreciated!

**Comment by Arcath** [comment]
Yeah, I found in #16 that it only works for markdown files...

I will look into what needs to be done to make everything inside --- formatted as yaml

**Comment by tjkohli** [comment]
That as well as the Jekyll logic & liquid tags, right?
Let me know if you need anything from me!
