### ISSUE TITLE
Please add support for custom folders (Source & Destination) & Templates / PostTypes

### ISSUE THREAD

**Issue by frankis** [Arcath/jekyll-atom#47]
As custom source/destination DIRS supported by Jekyll and many people (so am i) are using it, it would be great to see this being supported by allowing users of your atom add-in specifying those directories.

In specific, the following setting in_config.yml within Jekyll allow (for me) a much cleaner directory structure being used. 

```
# Structure configuration 
source: source
destination: build
```

Currently you add-in generates a new _posts folder in the root of the project.

While typing this:
Support for creating templates for different "PostTypes" for serving different purposes (pre populated categories, tags, collections,...) would be an awesome feature.

**Comment by Arcath** [comment]
I've updated the new post view to put posts into _posts and _drafts inside your source directory.

Would post templates work by having a drop down on new post to select a template and then putting it in _posts or should it move it to a custom folder?

**Comment by frankis** [comment]
Thanks! Will test once the update is available.

For Templates: 
- I am confident many people will love specifying a custom directory, however, I suggest setting the default to _posts
- Personally I would really love (!) being able if the template either reads from _config.yml what "posttypes" are present and allow specifying a template for each type found or, maybe a bit simpler, just allow custom config within the plugin to support specify post types (and an alias?) used and assigning a template to it.

Either way: It would be great being able to use different templates with individual frontmatter as it would ease up / clean up category/tag assignment, as well as working with different languages (which, if i18n enabled also could be an option to auto populate templates for each language defined).

Not sure if this makes sense to you. Just let me know and I am happy to dig into it more clearly.
