### ISSUE TITLE
Slugify post title

### ISSUE THREAD

**Issue by DirtyF** [Arcath/jekyll-atom#58]
Given I create a new post with jekyll-atom command with accents , e.g "J'ai aimé allé à l'aéroport"
Then the filename is `2016-11-08-jai-aime-alle-a-laeroport.markdown` (currently: `2016-11-08-jai-aim-all--laroport.mardown`)

**Comment by Arcath** [comment]
Using latinize I have got the filename to `2016-11-08-jai-aime-alle-a-laeroport.markdow` (missing the `-` where there was `'`). I'm unsure if this is enough, does it still convey the same meaning?

**Comment by DirtyF** [comment]
Yes, it's perfect, it follows https://tools.ietf.org/html/rfc3986.

**Comment by Arcath** [comment]
No problem!

I will publish a patch release asap.
