### ISSUE TITLE
Add user preference for post file extension

### ISSUE THREAD

**Issue by DirtyF** [Arcath/jekyll-atom#62]
Right now `.markdown` is forced by default: 
https://github.com/Arcath/jekyll-atom/blob/master/lib/jekyll/new-post-view.coffee#L83

What do you think of adding a user pref for post extension: {md, markdown} ?
default could stay to markdown, but if I choose `.md`, all new posts will have this extension.
Should it support other extensions beside Markdown ? 

If you agree, and tell me how to address this, I would happily try to submit a PR 😨

**Comment by Arcath** [comment]
Sounds like a great idea!

I'm thinking it might be better to add it to the `_config.yml` settings for `jekyll-atom` so it can be set per project.

**Comment by Arcath** [comment]
This was added in the latest release, I closed the wrong issue from the commit 😕
