### ISSUE TITLE
Permalinks "Not Found"

### ISSUE THREAD

**Issue by mickenorlen** [Arcath/jekyll-atom#64]
Hi,

I'm quite a beginner with both jekyll and atom. In my arch linux system the `jekyll serve` command works perfectly, producing pages and functional permalinks to posts from the _posts dir. 

When i start the jekyll server inside atom the pages and main navigation links are working; but if I set a permalink (e.g `permalink: /blog/:year/:title`) the links to my posts only lead me to a page echoing "Not Found". Is this a bug or am I missing some setting? 

I've tried  
`jekyll, build`  
`~/.gem/ruby/2.4.0/bin/jekyll, build`

in various versions...

The same permalinks work perfectly both on my system and github pages. Only the atom plugin server has this problem for some reason. And if I don't set a permalink the post links work as expected.

Thanks

**Comment by Arcath** [comment]
Is it your github pages site?

I will clone it to my machine and give it ago here.

**Comment by Arcath** [comment]
On my machine using the permalink `/blog/:year/:month/:day/:title/index.html` fixes the problem.

I'm not sure if this is a jekyll or static-server problem. Going through the generated site it's creating `/blog/2017/03/14/postname.html` which would require you to link to the html file.

**Comment by mickenorlen** [comment]
Your solution works. I didn't think about that I could look at the generated site for clues. Thanks for your quick help and the plugin too! Cheers

**Comment by Arcath** [comment]
Not a problem!

Glad its all working for you.
