### ISSUE TITLE
Cannot find settings

### ISSUE THREAD

**Issue by newton108** [Arcath/jekyll-atom#9]
I'm using atom 0.174.0. Cannot find settings under the package.
![screen shot 2015-01-16 at 04 10 21](https://cloud.githubusercontent.com/assets/3450659/5771471/aec1956e-9d35-11e4-8ea7-7e13befc870d.png)

**Comment by Arcath** [comment]
I've just updated to 0.174.0 and can confirm that the settings do not appear. Will do some testing now

**Comment by Arcath** [comment]
This is caused by this bug: https://github.com/atom/settings-view/issues/356

If you activate the package by opening anything (I suggest the new post window then close it) the settings will now appear

**Comment by Arcath** [comment]
This was fixed in atom
